In [23]:
import pandas as pd
from sqlalchemy import create_engine

import pymysql
pymysql.install_as_MySQLdb()

In [12]:
csv_file = "../team/sportsref_download_AFC_2018.csv"
AFC_df = pd.read_csv(csv_file)
AFC_df

,Tm,W,L,T,W-L%,PF,PA,PD,MoV,SoS,SRS,OSRS,DSRS
0,New England Patriots,11,5,0,0.688,436,325,111,6.9,-1.8,5.2,3.1,2.1
1,Miami Dolphins,7,9,0,0.438,319,433,-114,-7.1,-1.7,-8.8,-3.6,-5.2
2,Buffalo Bills,6,10,0,0.375,269,374,-105,-6.6,-0.3,-6.9,-6.3,-0.6
3,New York Jets,4,12,0,0.250,333,441,-108,-6.8,-1.1,-7.8,-2.0,-5.9
4,Baltimore Ravens,10,6,0,0.625,389,287,102,6.4,0.6,7.0,0.6,6.4
5,Pittsburgh Steelers,9,6,1,0.594,428,360,68,4.3,1.3,5.6,3.9,1.7
6,Cleveland Browns,7,8,1,0.469,359,392,-33,-2.1,1.7,-0.3,-1.0,0.6
7,Cincinnati Bengals,6,10,0,0.375,368,455,-87,-5.4,2.0,-3.4,0.0,-3.4
8,Houston Texans,11,5,0,0.688,402,316,86,5.4,-1.5,3.8,2.4,1.4
9,Indianapolis Colts,10,6,0,0.625,433,344,89,5.6,-2.2,3.4,3.9,-0.6
10,Tennessee Titans,9,7,0,0.563,310,303,7,0.4,-0.2,0.2,-3.2,3.5
11,Jacksonville Jaguars,5,11,0,0.313,245,316,-71,-4.4,0.4,-4.0,-8.1,4.0
12,Kansas City Chiefs,12,4,0,0.750,565,421,144,9.0,-0.1,8.9,12.6,-3.8
13,Los Angeles Chargers,12,4,0,0.750,428,329,99,6.2,-0.2,6.0,3.0,2.9
14,Denver Broncos,6,10,0,0.375,329,349,-20,-1.3,0.7,-0.5,-3.6,3.1
15,Oakland Raiders,4,12,0,0.250,290,467,-177,-11.1,1.8,-9.3,-5.2,-4.1

In [13]:
csv_file = "../team/sportsref_download_NFC_2018.csv"
NFC_df = pd.read_csv(csv_file)
NFC_df

,Tm,W,L,T,W-L%,PF,PA,PD,MoV,SoS,SRS,OSRS,DSRS
0,Dallas Cowboys,10,6,0,0.625,339,324,15,0.9,0.2,1.1,-1.9,2.9
1,Philadelphia Eagles,9,7,0,0.563,367,348,19,1.2,0.5,1.7,0.0,1.8
2,Washington Redskins,7,9,0,0.438,281,359,-78,-4.9,-0.1,-4.9,-5.6,0.6
3,New York Giants,5,11,0,0.313,369,412,-43,-2.7,0.5,-2.2,0.8,-2.9
4,Chicago Bears,12,4,0,0.750,421,283,138,8.6,-2.3,6.3,1.5,4.8
5,Minnesota Vikings,8,7,1,0.531,360,341,19,1.2,-0.6,0.6,-1.2,1.8
6,Green Bay Packers,6,9,1,0.406,376,400,-24,-1.5,-1.2,-2.7,0.0,-2.7
7,Detroit Lions,6,10,0,0.375,324,360,-36,-2.3,-0.8,-3.0,-3.3,0.3
8,New Orleans Saints,13,3,0,0.813,504,353,151,9.4,0.6,10.1,7.9,2.2
9,Carolina Panthers,7,9,0,0.438,376,382,-6,-0.4,1.3,0.9,0.1,0.8
10,Atlanta Falcons,7,9,0,0.438,414,423,-9,-0.6,0.4,-0.1,2.5,-2.6
11,Tampa Bay Buccaneers,5,11,0,0.313,396,464,-68,-4.3,1.7,-2.6,2.0,-4.6
12,Los Angeles Rams,13,3,0,0.813,527,384,143,8.9,-0.4,8.5,9.5,-1.1
13,Seattle Seahawks,10,6,0,0.625,428,347,81,5.1,-0.6,4.5,3.0,1.5
14,San Francisco 49ers,4,12,0,0.250,342,435,-93,-5.8,0.3,-5.5,-2.5,-3.1
15,Arizona Cardinals,3,13,0,0.188,225,425,-200,-12.5,1.0,-11.5,-9.6,-1.9

In [14]:
team_df = AFC_df.append(NFC_df)
team_df = team_df.reset_index(drop=True)
team_df

,Tm,W,L,T,W-L%,PF,PA,PD,MoV,SoS,SRS,OSRS,DSRS
0,New England Patriots,11,5,0,0.688,436,325,111,6.9,-1.8,5.2,3.1,2.1
1,Miami Dolphins,7,9,0,0.438,319,433,-114,-7.1,-1.7,-8.8,-3.6,-5.2
2,Buffalo Bills,6,10,0,0.375,269,374,-105,-6.6,-0.3,-6.9,-6.3,-0.6
3,New York Jets,4,12,0,0.250,333,441,-108,-6.8,-1.1,-7.8,-2.0,-5.9
4,Baltimore Ravens,10,6,0,0.625,389,287,102,6.4,0.6,7.0,0.6,6.4
5,Pittsburgh Steelers,9,6,1,0.594,428,360,68,4.3,1.3,5.6,3.9,1.7
6,Cleveland Browns,7,8,1,0.469,359,392,-33,-2.1,1.7,-0.3,-1.0,0.6
7,Cincinnati Bengals,6,10,0,0.375,368,455,-87,-5.4,2.0,-3.4,0.0,-3.4
8,Houston Texans,11,5,0,0.688,402,316,86,5.4,-1.5,3.8,2.4,1.4
9,Indianapolis Colts,10,6,0,0.625,433,344,89,5.6,-2.2,3.4,3.9,-0.6
10,Tennessee Titans,9,7,0,0.563,310,303,7,0.4,-0.2,0.2,-3.2,3.5
11,Jacksonville Jaguars,5,11,0,0.313,245,316,-71,-4.4,0.4,-4.0,-8.1,4.0
12,Kansas City Chiefs,12,4,0,0.750,565,421,144,9.0,-0.1,8.9,12.6,-3.8
13,Los Angeles Chargers,12,4,0,0.750,428,329,99,6.2,-0.2,6.0,3.0,2.9
14,Denver Broncos,6,10,0,0.375,329,349,-20,-1.3,0.7,-0.5,-3.6,3.1
15,Oakland Raiders,4,12,0,0.250,290,467,-177,-11.1,1.8,-9.3,-5.2,-4.1
16,Dallas Cowboys,10,6,0,0.625,339,324,15,0.9,0.2,1.1,-1.9,2.9
17,Philadelphia Eagles,9,7,0,0.563,367,348,19,1.2,0.5,1.7,0.0,1.8
18,Washington Redskins,7,9,0,0.438,281,359,-78,-4.9,-0.1,-4.9,-5.6,0.6
19,New York Giants,5,11,0,0.313,369,412,-43,-2.7,0.5,-2.2,0.8,-2.9
20,Chicago Bears,12,4,0,0.750,421,283,138,8.6,-2.3,6.3,1.5,4.8
21,Minnesota Vikings,8,7,1,0.531,360,341,19,1.2,-0.6,0.6,-1.2,1.8
22,Green Bay Packers,6,9,1,0.406,376,400,-24,-1.5,-1.2,-2.7,0.0,-2.7
23,Detroit Lions,6,10,0,0.375,324,360,-36,-2.3,-0.8,-3.0,-3.3,0.3
24,New Orleans Saints,13,3,0,0.813,504,353,151,9.4,0.6,10.1,7.9,2.2
25,Carolina Panthers,7,9,0,0.438,376,382,-6,-0.4,1.3,0.9,0.1,0.8
26,Atlanta Falcons,7,9,0,0.438,414,423,-9,-0.6,0.4,-0.1,2.5,-2.6
27,Tampa Bay Buccaneers,5,11,0,0.313,396,464,-68,-4.3,1.7,-2.6,2.0,-4.6
28,Los Angeles Rams,13,3,0,0.813,527,384,143,8.9,-0.4,8.5,9.5,-1.1
29,Seattle Seahawks,10,6,0,0.625,428,347,81,5.1,-0.6,4.5,3.0,1.5
30,San Francisco 49ers,4,12,0,0.250,342,435,-93,-5.8,0.3,-5.5,-2.5,-3.1
31,Arizona Cardinals,3,13,0,0.188,225,425,-200,-12.5,1.0,-11.5,-9.6,-1.9

In [15]:
team_df = team_df.rename(columns = {"Tm":"Team"})
team_df

,Team,W,L,T,W-L%,PF,PA,PD,MoV,SoS,SRS,OSRS,DSRS
0,New England Patriots,11,5,0,0.688,436,325,111,6.9,-1.8,5.2,3.1,2.1
1,Miami Dolphins,7,9,0,0.438,319,433,-114,-7.1,-1.7,-8.8,-3.6,-5.2
2,Buffalo Bills,6,10,0,0.375,269,374,-105,-6.6,-0.3,-6.9,-6.3,-0.6
3,New York Jets,4,12,0,0.250,333,441,-108,-6.8,-1.1,-7.8,-2.0,-5.9
4,Baltimore Ravens,10,6,0,0.625,389,287,102,6.4,0.6,7.0,0.6,6.4
5,Pittsburgh Steelers,9,6,1,0.594,428,360,68,4.3,1.3,5.6,3.9,1.7
6,Cleveland Browns,7,8,1,0.469,359,392,-33,-2.1,1.7,-0.3,-1.0,0.6
7,Cincinnati Bengals,6,10,0,0.375,368,455,-87,-5.4,2.0,-3.4,0.0,-3.4
8,Houston Texans,11,5,0,0.688,402,316,86,5.4,-1.5,3.8,2.4,1.4
9,Indianapolis Colts,10,6,0,0.625,433,344,89,5.6,-2.2,3.4,3.9,-0.6
10,Tennessee Titans,9,7,0,0.563,310,303,7,0.4,-0.2,0.2,-3.2,3.5
11,Jacksonville Jaguars,5,11,0,0.313,245,316,-71,-4.4,0.4,-4.0,-8.1,4.0
12,Kansas City Chiefs,12,4,0,0.750,565,421,144,9.0,-0.1,8.9,12.6,-3.8
13,Los Angeles Chargers,12,4,0,0.750,428,329,99,6.2,-0.2,6.0,3.0,2.9
14,Denver Broncos,6,10,0,0.375,329,349,-20,-1.3,0.7,-0.5,-3.6,3.1
15,Oakland Raiders,4,12,0,0.250,290,467,-177,-11.1,1.8,-9.3,-5.2,-4.1
16,Dallas Cowboys,10,6,0,0.625,339,324,15,0.9,0.2,1.1,-1.9,2.9
17,Philadelphia Eagles,9,7,0,0.563,367,348,19,1.2,0.5,1.7,0.0,1.8
18,Washington Redskins,7,9,0,0.438,281,359,-78,-4.9,-0.1,-4.9,-5.6,0.6
19,New York Giants,5,11,0,0.313,369,412,-43,-2.7,0.5,-2.2,0.8,-2.9
20,Chicago Bears,12,4,0,0.750,421,283,138,8.6,-2.3,6.3,1.5,4.8
21,Minnesota Vikings,8,7,1,0.531,360,341,19,1.2,-0.6,0.6,-1.2,1.8
22,Green Bay Packers,6,9,1,0.406,376,400,-24,-1.5,-1.2,-2.7,0.0,-2.7
23,Detroit Lions,6,10,0,0.375,324,360,-36,-2.3,-0.8,-3.0,-3.3,0.3
24,New Orleans Saints,13,3,0,0.813,504,353,151,9.4,0.6,10.1,7.9,2.2
25,Carolina Panthers,7,9,0,0.438,376,382,-6,-0.4,1.3,0.9,0.1,0.8
26,Atlanta Falcons,7,9,0,0.438,414,423,-9,-0.6,0.4,-0.1,2.5,-2.6
27,Tampa Bay Buccaneers,5,11,0,0.313,396,464,-68,-4.3,1.7,-2.6,2.0,-4.6
28,Los Angeles Rams,13,3,0,0.813,527,384,143,8.9,-0.4,8.5,9.5,-1.1
29,Seattle Seahawks,10,6,0,0.625,428,347,81,5.1,-0.6,4.5,3.0,1.5
30,San Francisco 49ers,4,12,0,0.250,342,435,-93,-5.8,0.3,-5.5,-2.5,-3.1
31,Arizona Cardinals,3,13,0,0.188,225,425,-200,-12.5,1.0,-11.5,-9.6,-1.9

In [16]:
team_df["Tm"] = ["NE","MIA","BUF","NYJ","BAL","PIT","CLE","CIN","HOU","IND","TEN","JAX","KC","LAC","DEN","OAK","DAL",
                 "PHI","WAS","NYG","CHI","MIN","GB","DET","NO","CAR","ALT","TB","LAR","SEA","SF","ARI"]
team_df

,Team,W,L,T,W-L%,PF,PA,PD,MoV,SoS,SRS,OSRS,DSRS,Tm
0,New England Patriots,11,5,0,0.688,436,325,111,6.9,-1.8,5.2,3.1,2.1,NE
1,Miami Dolphins,7,9,0,0.438,319,433,-114,-7.1,-1.7,-8.8,-3.6,-5.2,MIA
2,Buffalo Bills,6,10,0,0.375,269,374,-105,-6.6,-0.3,-6.9,-6.3,-0.6,BUF
3,New York Jets,4,12,0,0.250,333,441,-108,-6.8,-1.1,-7.8,-2.0,-5.9,NYJ
4,Baltimore Ravens,10,6,0,0.625,389,287,102,6.4,0.6,7.0,0.6,6.4,BAL
5,Pittsburgh Steelers,9,6,1,0.594,428,360,68,4.3,1.3,5.6,3.9,1.7,PIT
6,Cleveland Browns,7,8,1,0.469,359,392,-33,-2.1,1.7,-0.3,-1.0,0.6,CLE
7,Cincinnati Bengals,6,10,0,0.375,368,455,-87,-5.4,2.0,-3.4,0.0,-3.4,CIN
8,Houston Texans,11,5,0,0.688,402,316,86,5.4,-1.5,3.8,2.4,1.4,HOU
9,Indianapolis Colts,10,6,0,0.625,433,344,89,5.6,-2.2,3.4,3.9,-0.6,IND
10,Tennessee Titans,9,7,0,0.563,310,303,7,0.4,-0.2,0.2,-3.2,3.5,TEN
11,Jacksonville Jaguars,5,11,0,0.313,245,316,-71,-4.4,0.4,-4.0,-8.1,4.0,JAX
12,Kansas City Chiefs,12,4,0,0.750,565,421,144,9.0,-0.1,8.9,12.6,-3.8,KC
13,Los Angeles Chargers,12,4,0,0.750,428,329,99,6.2,-0.2,6.0,3.0,2.9,LAC
14,Denver Broncos,6,10,0,0.375,329,349,-20,-1.3,0.7,-0.5,-3.6,3.1,DEN
15,Oakland Raiders,4,12,0,0.250,290,467,-177,-11.1,1.8,-9.3,-5.2,-4.1,OAK
16,Dallas Cowboys,10,6,0,0.625,339,324,15,0.9,0.2,1.1,-1.9,2.9,DAL
17,Philadelphia Eagles,9,7,0,0.563,367,348,19,1.2,0.5,1.7,0.0,1.8,PHI
18,Washington Redskins,7,9,0,0.438,281,359,-78,-4.9,-0.1,-4.9,-5.6,0.6,WAS
19,New York Giants,5,11,0,0.313,369,412,-43,-2.7,0.5,-2.2,0.8,-2.9,NYG
20,Chicago Bears,12,4,0,0.750,421,283,138,8.6,-2.3,6.3,1.5,4.8,CHI
21,Minnesota Vikings,8,7,1,0.531,360,341,19,1.2,-0.6,0.6,-1.2,1.8,MIN
22,Green Bay Packers,6,9,1,0.406,376,400,-24,-1.5,-1.2,-2.7,0.0,-2.7,GB
23,Detroit Lions,6,10,0,0.375,324,360,-36,-2.3,-0.8,-3.0,-3.3,0.3,DET
24,New Orleans Saints,13,3,0,0.813,504,353,151,9.4,0.6,10.1,7.9,2.2,NO
25,Carolina Panthers,7,9,0,0.438,376,382,-6,-0.4,1.3,0.9,0.1,0.8,CAR
26,Atlanta Falcons,7,9,0,0.438,414,423,-9,-0.6,0.4,-0.1,2.5,-2.6,ALT
27,Tampa Bay Buccaneers,5,11,0,0.313,396,464,-68,-4.3,1.7,-2.6,2.0,-4.6,TB
28,Los Angeles Rams,13,3,0,0.813,527,384,143,8.9,-0.4,8.5,9.5,-1.1,LAR
29,Seattle Seahawks,10,6,0,0.625,428,347,81,5.1,-0.6,4.5,3.0,1.5,SEA
30,San Francisco 49ers,4,12,0,0.250,342,435,-93,-5.8,0.3,-5.5,-2.5,-3.1,SF
31,Arizona Cardinals,3,13,0,0.188,225,425,-200,-12.5,1.0,-11.5,-9.6,-1.9,ARI

In [17]:
team_df.columns

Index(['Team', 'W', 'L', 'T', 'W-L%', 'PF', 'PA', 'PD', 'MoV', 'SoS', 'SRS',
       'OSRS', 'DSRS', 'Tm'],
      dtype='object')

In [18]:
team_df = team_df[['Team', 'Tm', 'W', 'L', 'T', 'W-L%', 'PF', 'PA', 'PD', 'MoV', 'SoS', 'SRS',
       'OSRS', 'DSRS']]
team_df.head()

,Team,Tm,W,L,T,W-L%,PF,PA,PD,MoV,SoS,SRS,OSRS,DSRS
0,New England Patriots,NE,11,5,0,0.688,436,325,111,6.9,-1.8,5.2,3.1,2.1
1,Miami Dolphins,MIA,7,9,0,0.438,319,433,-114,-7.1,-1.7,-8.8,-3.6,-5.2
2,Buffalo Bills,BUF,6,10,0,0.375,269,374,-105,-6.6,-0.3,-6.9,-6.3,-0.6
3,New York Jets,NYJ,4,12,0,0.250,333,441,-108,-6.8,-1.1,-7.8,-2.0,-5.9
4,Baltimore Ravens,BAL,10,6,0,0.625,389,287,102,6.4,0.6,7.0,0.6,6.4

Transform data

In [19]:
team_df = team_df[['Team', 'Tm', 'W', 'L', 'T', 'W-L%', 'PF', 'PA', 'PD']].copy()
team_df.head()

                   Team   Tm   W   L  T   W-L%   PF   PA   PD
0  New England Patriots   NE  11   5  0  0.688  436  325  111
1        Miami Dolphins  MIA   7   9  0  0.438  319  433 -114
2         Buffalo Bills  BUF   6  10  0  0.375  269  374 -105
3         New York Jets  NYJ   4  12  0  0.250  333  441 -108
4      Baltimore Ravens  BAL  10   6  0  0.625  389  287  102

creat database connection

In [24]:
connection_string = "root:<root>@localhost/nfl_db"
engine = create_engine(f'mysql://{connection_string}')

In [27]:
engine.table_names()

OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'172.17.0.1' (using password: YES)")
(Background on this error at: http://sqlalche.me/e/e3q8)